#
# AllenNLP
#
# https://github.com/allenai/allennlp
#

# Pull base image.
FROM allennlp/allennlp

MAINTAINER Alex Cai "cyy0523xc@gmail.com"


# 解决时区问题
ENV TZ "Asia/Shanghai"

# 终端设置
ENV TERM xterm

# Define mountable directories.
VOLUME /var/www

# 工作目录
WORKDIR /var/www 
